### ISSUE TITLE
Teléfono fijo

### ISSUE THREAD

**Issue by juanbits** [fasaro/magento2-es_mx-language-pack#1]
Considero que la traducción de:
"Phone Number" que actualmente se traduce como "Teléfono fijo" se cambie a "Número de Teléfono" o en el caso de México "Número de Teléfono (10 dígitos)", considerando que los números fijos cada vez son menos utilizados y sea el usuario quien decida que numero incluir, ya que puede también prestarse a confusión que el usuario no tenga un numero fijo y considere que no puede poner su numero de celular

**Comment by fasaro** [comment]
hola Juan Carlos, gracias por tu comentario lo estaremos revisando para el
siguiente upgrarde. saludos!
