### ISSUE TITLE
Installation failed!!!

### ISSUE THREAD

**Issue by lexcorp** [fasaro/magento2-es_mx-language-pack#2]
composer require fasaro/magento2-es_mx-language-pack dev-master
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for fasaro/magento2-es_mx-language-pack dev-master -> satisfiable by fasaro/magento2-es_mx-language-pack[dev-master].
    - fasaro/magento2-es_mx-language-pack dev-master requires magento/framework * -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, deleting ./composer.json.

**Comment by fasaro** [comment]
hi Lexcorp, what version of magento are you using?
