### ISSUE TITLE
traducir cadena que no viene en el es_MX.csv

### ISSUE THREAD

**Issue by juanbits** [fasaro/magento2-es_mx-language-pack#5]
Hola @fasaro , tengo un problema, en mi theme (theme/Magento_Checkout/web/template/minicart/content.html) en el modulo Magento_Checkout viene una cadena asi:
```
               <div class="secondary">
                    <a class="action viewcart" data-bind="attr: {href: shoppingCartUrl}">
                        <span translate="'View Cart'"/>
                    </a>
                </div>
```

Intente agregar la siguiente línea 
`"View Cart","Ver Carrito","module","Magento_Checkout"`

al final del archivo es_MX.csv de tu traducción directamente en el archivo dentro de magento
`vendor/fasaro/magento2-es_mx-language-pack/es_MX.csv`

pero sigue apareciendo View Cart en el frontend, mi deploy está en modo development, entonces entiendo que no hay necesidad de estar haciendo el deployment de los archivos estáticos, de todos modos limpie la cache.

perdon por el off-topic, alguna sugerencia?

gracias

**Comment by fasaro** [comment]
Hola Juan Carlos, gracias por tu mensaje. dejame lo reviso y te confirmo.
va!

**Comment by fasaro** [comment]
Hola @juanbits que theme estas utlizando? ya que con LUMA el theme original de Magento no hay ningun error. 

Saludos!

**Comment by juanbits** [comment]
Hola @fasaro ,
el theme que estoy ocupando es Athlete de Olegnax

**Comment by fasaro** [comment]
Hola @juanbits ya quedo solucionado, para reflejar los cambios sigue estos pasos desde tu terminal SSH en la carpeta root de tu magento;

```
rm -rf var/di/* var/generation/* var/cache/* var/log/* var/page_cache/* var/session/* var/view_preprocessed/* pub/static/*
composer update fasaro/magento2-es_mx-language-pack dev-master
php bin/magento setup:static-content:deploy es_MX
php bin/magento indexer:reindex
php bin/magento cache:clean
php bin/magento cache:flush
```

Adicional hay que borrar caches (redis, varnish, lsws, etc)
Abre un nuevo navegador y lo compruebas, de no verse reflejado el cambio tienes que borrar tambien el cache de tu navegador. 

Saludos!
